# Overview of types of values:
# String: Strings are encased in "". Any text or snowflake (Discord ID) is a string and needs to be encased "".
# Number: Numbers are not enclosed in "". They are just numbers and are not interpreted by the bot the same way that strings are.
# Array: Array is just a list of other types. Could be numbers, strings, or objects. each item is separated by a comma. Example: [ "first ID", "second ID" ]
# Object: Objects are, in this case, structures with a key and value pair. Key is the first item, value is the second item. There can also be arrays of objects.
# Boolean: Booleans are just true or false. Do NOT encase them with "". They are meant to just be true or false by themselves.
# This guide can help you create a bot and invite it to your server: https:#discordjs.guide/preparations/setting-up-a-bot-application.html
# This site can help you create an invite link for your bot: https:#discordapi.com/permissions.html
# This bot was coded to only work on servers that are configured here. Do not make your bot public, it will only create errors and break things.
# Make sure you have created a config.js file before running the bot. The bot will not run using only the example.config.js file.

# Follow this guide to create your bot and get it's token/invite it to your server: https://discordjs.guide/preparations/setting-up-a-bot-application.html
token = "."

# The ID of your bot, you can get this from your bot's application page. It will be called "Application ID"
clientId = "1104630573772841070"

# Maximum CPU threads the bot should use for it's worker thread pool
cpuThreads = 4
guildId = "1190156169961029774"
botOwnerID = "478044823882825748"
appealServer = "https:#discord.gg/wJhppSMHpG"

[status]
type = 3
content = "over everyone"

[colors]
success = "#66de98"
error = "#FF6961"
main = "#6C4678"
warning = "#f5f562"

[emojis]
sent = "<:sent:1203188998097604608>"
yes = "<:check:1203191199251300402>"
no = "<:x_:1203191562084032594>"
success = "<:check:1203191199251300402>"
error = "<:x_:1203191562084032594>"
loading = "<a:loading:1206460809623113758>"

[server]
enabled = true
PORT = 1746
url = "https://learn.tokyo.jp/fern"

# IMPORTANT: Once you're done setting this file up, ensure you also do your guild configs, located in the 'guilds' folder.
# Copy the "blank.toml" file and paste it. Rename it to the name of your guild, then fill out the information inside.
# Do this for every single guild you want the bot to be in. Each guild should have it's own toml file by the end.
# When done, open the root folder where "package.json" is located and run the command "npm run generateConf"
